package com.mycompany.ql_mua_ban_dong_ho;
import com.mycompany.ql_mua_ban_dong_ho.Giao_dien_chính;

/**
 *
 * @author ASUS
 */
public class Lienhe extends javax.swing.JFrame {
    private Giao_dien_chính mainForm;
public Lienhe() {
        initComponents();
        this.setLocationRelativeTo(null);
        // Không thêm MouseListener cho nút thoat,vì hàm tạo này không nhận tham chiếu đến form chính.
    }

    /**
     * Creates new form Lienhe
     */
    public Lienhe(Giao_dien_chính mainForm) { 
        initComponents();
        this.mainForm = mainForm;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thoat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trolai.png"))); // NOI18N
        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });
        getContentPane().add(thoat);
        thoat.setBounds(310, 370, 80, 40);

        jLabel2.setBackground(new java.awt.Color(27, 69, 25));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   BẠN MUỐN LIÊN HỆ MÌNH ?");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 2, 890, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Email: htha4067@gmail.com");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 160, 240, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Họ tên: Huỳnh Thanh Hoàng Anh");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 60, 210, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("MSSV: 0023411989");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 90, 190, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Địa chỉ: Phương Trà, Cao Lãnh, Đồng Tháp");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 130, 280, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ngày sinh: 11/ tháng đẹp nhất trong năm");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 110, 270, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Đồng hồ mua rồi miễn trả lại !");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 250, 240, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Chủ đề: Quản lý mua bán đồng hồ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 220, 240, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tuổi: 18 ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 90, 190, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Hiện tại: muốn điểm cao !");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 200, 240, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Sở thích: đủ thứ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 180, 240, 20);

        jLabel1.setBackground(new java.awt.Color(185, 199, 185));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 44, 460, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatActionPerformed
        // TODO add your handling code here:
        if (this.mainForm != null) { 
            this.mainForm.setVisible(true);
        }
        // Đóng form Liên hệ hiện tại
        this.dispose(); 
    
    }//GEN-LAST:event_thoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lienhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lienhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lienhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lienhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lienhe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton thoat;
    // End of variables declaration//GEN-END:variables
}
