package com.mycompany.ql_mua_ban_dong_ho;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class modau extends javax.swing.JFrame {

    /**
     * Creates new form modau
     */
    public modau() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        nhapmatkhau = new javax.swing.JPasswordField();
        hienmatkhau = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nutdangnhap = new javax.swing.JButton();
        tendangnhap = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));
        getContentPane().setLayout(null);

        jLabel13.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("HOÀNG ANH APACHE");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 120, 360, 110);

        nhapmatkhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(nhapmatkhau);
        nhapmatkhau.setBounds(430, 190, 260, 50);

        hienmatkhau.setText("Hiện mật khẩu");
        hienmatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hienmatkhauActionPerformed(evt);
            }
        });
        getContentPane().add(hienmatkhau);
        hienmatkhau.setBounds(600, 250, 110, 20);

        jLabel12.setText("Tạo tài khoản mới");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(590, 360, 100, 30);

        jLabel11.setText("Quên mật khẩu?");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 360, 100, 30);

        nutdangnhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nutdangnhap.setText("Đăng nhập");
        nutdangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutdangnhapActionPerformed(evt);
            }
        });
        getContentPane().add(nutdangnhap);
        nutdangnhap.setBounds(430, 280, 260, 50);

        tendangnhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tendangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tendangnhapActionPerformed(evt);
            }
        });
        getContentPane().add(tendangnhap);
        tendangnhap.setBounds(430, 90, 260, 50);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Nhập mật khẩu:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 150, 130, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mã/ Tên đăng nhập:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 50, 130, 30);

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MUA BÁN ĐỒNG HỒ ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 70, 360, 110);

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PHẦM MỀM QUẢN LÝ ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 30, 360, 110);

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("     Vui lòng đăng nhập để tiếp tục !");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 320, 330, 30);

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("quản lý mua bán đồng hồ ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 340, 250, 40);

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Chào mừng bạn đến với hệ thống ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 290, 330, 30);

        jLabel2.setBackground(new java.awt.Color(216, 231, 218));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 30, 320, 410);

        jLabel3.setBackground(new java.awt.Color(120, 137, 125));
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 210, 330, 130);

        jLabel1.setBackground(new java.awt.Color(0, 102, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nen.png"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tendangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tendangnhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tendangnhapActionPerformed

    private void nutdangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutdangnhapActionPerformed
        // TODO add your handling code here:
    String nguoidung = tendangnhap.getText().trim();
    String pass = nhapmatkhau.getText().trim();
    // Tài khoản mặc định
    if (nguoidung.equals("Hoang Anh") && pass.equals("admin123")) {
        new Giao_dien_chính(nguoidung).setVisible(true); // Truyền tên người dùng  
        this.dispose(); // đóng form hiện tại
    } else {
        JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc mật khẩu!", "Lỗi đăng nhập", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_nutdangnhapActionPerformed

    private void hienmatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hienmatkhauActionPerformed
        // TODO add your handling code here:
        if(hienmatkhau.isSelected()){     // chọn thì hiện mật khẩu ko chọn thì để dấu *
            nhapmatkhau.setEchoChar((char)0);
} else{
            nhapmatkhau.setEchoChar('*');  //ký tự ẩn
        }
   
    }//GEN-LAST:event_hienmatkhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modau().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox hienmatkhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField nhapmatkhau;
    private javax.swing.JButton nutdangnhap;
    private javax.swing.JTextField tendangnhap;
    // End of variables declaration//GEN-END:variables
}
