package com.mycompany.ql_mua_ban_dong_ho;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;


/**
 *
 * @author ASUS
 */
public class mua extends javax.swing.JFrame {
    private final String maDongHo;
    private final String tenDongHo;
    private final String thuongHieu;
    private final double gia;
    private final int soLuongTon; // Số lượng sản phẩm CÓ TRONG KHO
    private final Giao_dien_chính mainForm;

    /**
     * Creates new form mua
     */
   public mua(Giao_dien_chính mainForm, String maDongHo, String tenDongHo, String thuongHieu, double gia, int soLuongTon) {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        // Gán giá trị từ tham số vào biến thành viên của lớp
        this.mainForm = mainForm;
        this.maDongHo = maDongHo;
        this.tenDongHo = tenDongHo;
        this.thuongHieu = thuongHieu;
        this.gia = gia;
        this.soLuongTon = soLuongTon;

        // Hiển thị thông tin lên các JLabel (giả sử bạn đã đặt tên chúng là tenDHLabel, thuongHieuLabel, etc.)
        jLabel7.setText(tenDongHo);       // Tên đồng hồ
        jLabel8.setText(thuongHieu);     // Thương hiệu
        soluong.setText(String.valueOf(soLuongTon)); // Số lượng
        
        
        // Định dạng giá tiền cho dễ đọc
        DecimalFormat df = new DecimalFormat("#,### VNĐ");
        jLabel10.setText(df.format(gia)); // Giá
 addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                quayLaiMainForm();
            }
        });
    }
   private void quayLaiMainForm() {
        this.dispose();
        if (mainForm != null) {
            mainForm.enableMainForm(); // Kích hoạt lại form chính
        }
    }
    
    // Phương thức để form Hoadon có thể enable lại form này
    public void enableMuaForm() {
        this.setEnabled(true);
        this.setVisible(true);
    }
        // Thêm hàm khởi tạo mặc định này vào trong lớp `mua`
    private mua() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Vô hiệu hóa nút và thông báo vì không có dữ liệu sản phẩm
            this.mainForm = null;
    this.maDongHo = "";
    this.tenDongHo = "";
    this.thuongHieu = "";
    this.gia = 0;
    this.soLuongTon = 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        xacnhan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        quaylai = new javax.swing.JButton();
        soluong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên đồng hồ:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 64, 130, 20);

        xacnhan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        xacnhan.setText("Xác nhận");
        xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacnhanActionPerformed(evt);
            }
        });
        getContentPane().add(xacnhan);
        xacnhan.setBounds(190, 256, 74, 32);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 94, 120, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 64, 150, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Thương hiệu:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 94, 90, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Số lượng:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 124, 60, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Giá:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 154, 30, 20);

        quaylai.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        quaylai.setText("Quay lại");
        quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaylaiActionPerformed(evt);
            }
        });
        getContentPane().add(quaylai);
        quaylai.setBounds(84, 256, 72, 32);

        soluong.setBackground(new java.awt.Color(158, 186, 155));
        soluong.setOpaque(true);
        soluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soluongActionPerformed(evt);
            }
        });
        getContentPane().add(soluong);
        soluong.setBounds(80, 124, 71, 22);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 154, 120, 20);

        jLabel2.setBackground(new java.awt.Color(27, 69, 25));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("      Chọn sản phẩm");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 270, 50);

        jLabel3.setBackground(new java.awt.Color(158, 186, 155));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 50, 270, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacnhanActionPerformed
        // TODO add your handling code here:
     int soLuongMua;
    try {
        // Sửa lại tên biến cho đúng với file của bạn, có thể là soluong hoặc txtSoLuongMua
        soLuongMua = Integer.parseInt(soluong.getText().trim()); 
        if (soLuongMua <= 0) {
            JOptionPane.showMessageDialog(this, "Số lượng mua phải là số dương.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // THÊM ĐOẠN KIỂM TRA NÀY
        if (soLuongMua > this.soLuongTon) {
            JOptionPane.showMessageDialog(this, "Số lượng mua không được vượt quá số lượng tồn kho (" + this.soLuongTon + ").", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng mua hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

        // Vô hiệu hóa và ẩn form hiện tại
        this.setEnabled(false);
        this.setVisible(false);
        
        // Mở form Hoadon và truyền tất cả thông tin cần thiết
        new Hoadon(this.mainForm, this, this.maDongHo, this.tenDongHo, this.thuongHieu, this.gia, soLuongMua).setVisible(true);
   
    
    }//GEN-LAST:event_xacnhanActionPerformed

    private void quaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaylaiActionPerformed
        // TODO add your handling code here:
                quayLaiMainForm();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         java.awt.EventQueue.invokeLater(() -> new mua().setVisible(true));

    }//GEN-LAST:event_quaylaiActionPerformed

    private void soluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soluongActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton quaylai;
    private javax.swing.JTextField soluong;
    private javax.swing.JButton xacnhan;
    // End of variables declaration//GEN-END:variables

}